version: '3.8'


services:

  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl/cert.crt:/etc/nginx/certs/cert.crt
      - ./ssl/private.key:/etc/nginx/certs/private.key
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - auctionservice
      - playerservice
      - userservice
      - duckservice
    networks:
      - django-network
  db:
    image: postgres:14  
    container_name: postgres_container
    environment:
      POSTGRES_USER: gachadb
      POSTGRES_PASSWORD: gachadb
      POSTGRES_DB: gacha
      
    ports:
      - 5432
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - django-network

  auctionservice:
    build:
      context: ./auctionservice
      dockerfile: Dockerfile
    container_name: auctionservice
    ports:
      - "8001:8001"
    volumes:
      - ./auctionservice:/auctionservice
    depends_on:
      - db
    environment:
      POSTGRES_USER: gachadb
      POSTGRES_PASSWORD: gachadb
      POSTGRES_DB: gacha
    networks:
      - django-network

  duckservice:
    build:
      context: ./duckservice
      dockerfile: Dockerfile
    container_name: duckservice
    ports:
      - "8002:8002"
    volumes:
      - ./duckservice:/duckservice
    depends_on:
      - db 
    environment:
     
      POSTGRES_USER: gachadb
      POSTGRES_PASSWORD: gachadb
      POSTGRES_DB: gacha
    networks:
      - django-network

  playerservice:
    build:
      context: ./playerservice
      dockerfile: Dockerfile
    container_name: playerservice
    ports:
      - "8003:8003"
    volumes:
      - ./playerservice:/playerservice
    depends_on:
      - db 
    environment:
     
      POSTGRES_USER: gachadb
      POSTGRES_PASSWORD: gachadb
      POSTGRES_DB: gacha
    networks:
      - django-network

  userservice:
    build:
      context: ./userservice
      dockerfile: Dockerfile
    container_name: userservice
    ports:
      - "8004:8004"
    volumes:
      - ./userservice:/userservice
    depends_on:
      - db
    environment:
      POSTGRES_USER: gachadb
      POSTGRES_PASSWORD: gachadb
      POSTGRES_DB: gacha
    networks:
      - django-network

volumes:


  db_data:

networks:
  django-network:
