# Generated by Django 5.1.2 on 2024-10-15 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Duck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("C", "Common"),
                            ("R", "Rare"),
                            ("SR", "SuperRare"),
                            ("UR", "UltraRare"),
                            ("SUR", "SuperUltraRare"),
                        ],
                        max_length=3,
                    ),
                ),
                ("profession", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Auction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "starting_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "current_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("end_time", models.DateTimeField()),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "duck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.duck"
                    ),
                ),
            ],
        ),
    ]
