# Generated by Django 5.1.3 on 2024-11-12 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_duck_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDuck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_collected", models.DateTimeField(auto_now_add=True)),
                (
                    "duck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.duck"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="duck",
            name="owners",
            field=models.ManyToManyField(
                related_name="collected_ducks",
                through="api.UserDuck",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
