# Generated by Django 5.1.3 on 2024-11-09 16:30

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_auction_highest_bidder_remove_auction_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='highest_bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bids', to='api.player'),
        ),
        migrations.AddField(
            model_name='auction',
            name='seller',
            field=models.ForeignKey(default=api.models.get_default_seller, on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='api.player'),
        ),
    ]
