# Generated by Django 4.2.16 on 2024-11-21 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_userduck_duck_owners"),
        ("api", "0005_auction_highest_bidder_auction_seller"),
    ]

    operations = []
