# Generated by Django 5.1.2 on 2024-10-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="duck",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="ducks/"),
        ),
    ]
